[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && NODE_OPTIONS=--max-old-space-size=512 npm run build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
